//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicPhotos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagicPhotos.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ApplicationBarButtonHelpText {
            get {
                return ResourceManager.GetString("ApplicationBarButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ApplicationBarButtonSaveText {
            get {
                return ResourceManager.GetString("ApplicationBarButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ApplicationBarButtonSettingsText {
            get {
                return ResourceManager.GetString("ApplicationBarButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string BlurPreviewPageButtonApplyContent {
            get {
                return ResourceManager.GetString("BlurPreviewPageButtonApplyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLUR PARAMETERS.
        /// </summary>
        public static string BlurPreviewPageTextBlockPageCommentText {
            get {
                return ResourceManager.GetString("BlurPreviewPageTextBlockPageCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur:.
        /// </summary>
        public static string BlurPreviewPageTextBlockSliderCommentText {
            get {
                return ResourceManager.GetString("BlurPreviewPageTextBlockSliderCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string CartoonPreviewPageButtonApplyContent {
            get {
                return ResourceManager.GetString("CartoonPreviewPageButtonApplyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing:.
        /// </summary>
        public static string CartoonPreviewPageTextBlockGaussianRadiusSliderCommentText {
            get {
                return ResourceManager.GetString("CartoonPreviewPageTextBlockGaussianRadiusSliderCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARTOON PARAMETERS.
        /// </summary>
        public static string CartoonPreviewPageTextBlockPageCommentText {
            get {
                return ResourceManager.GetString("CartoonPreviewPageTextBlockPageCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness:.
        /// </summary>
        public static string CartoonPreviewPageTextBlockThresholdSliderCommentText {
            get {
                return ResourceManager.GetString("CartoonPreviewPageTextBlockThresholdSliderCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        public static string MainPageButtonOpenImageContent {
            get {
                return ResourceManager.GetString("MainPageButtonOpenImageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur.
        /// </summary>
        public static string MainPagePivotItemBlurHeader {
            get {
                return ResourceManager.GetString("MainPagePivotItemBlurHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoon.
        /// </summary>
        public static string MainPagePivotItemCartoonHeader {
            get {
                return ResourceManager.GetString("MainPagePivotItemCartoonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decolorize.
        /// </summary>
        public static string MainPagePivotItemDecolorizeHeader {
            get {
                return ResourceManager.GetString("MainPagePivotItemDecolorizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixelate.
        /// </summary>
        public static string MainPagePivotItemPixelateHeader {
            get {
                return ResourceManager.GetString("MainPagePivotItemPixelateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolor.
        /// </summary>
        public static string MainPagePivotItemRecolorHeader {
            get {
                return ResourceManager.GetString("MainPagePivotItemRecolorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retouch.
        /// </summary>
        public static string MainPagePivotItemRetouchHeader {
            get {
                return ResourceManager.GetString("MainPagePivotItemRetouchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch.
        /// </summary>
        public static string MainPagePivotItemSketchHeader {
            get {
                return ResourceManager.GetString("MainPagePivotItemSketchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE EDIT MODE.
        /// </summary>
        public static string MainPagePivotTitle {
            get {
                return ResourceManager.GetString("MainPagePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxHeaderError {
            get {
                return ResourceManager.GetString("MessageBoxHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageBoxHeaderInfo {
            get {
                return ResourceManager.GetString("MessageBoxHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxHeaderWarning {
            get {
                return ResourceManager.GetString("MessageBoxHeaderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open image:.
        /// </summary>
        public static string MessageBoxMessageImageOpenError {
            get {
                return ResourceManager.GetString("MessageBoxMessageImageOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved successfully..
        /// </summary>
        public static string MessageBoxMessageImageSavedInfo {
            get {
                return ResourceManager.GetString("MessageBoxMessageImageSavedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save image:.
        /// </summary>
        public static string MessageBoxMessageImageSaveError {
            get {
                return ResourceManager.GetString("MessageBoxMessageImageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open Marketplace:.
        /// </summary>
        public static string MessageBoxMessageMarketplaceOpenError {
            get {
                return ResourceManager.GetString("MessageBoxMessageMarketplaceOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save function is available in the full version only. Do you want to purchase full version now?.
        /// </summary>
        public static string MessageBoxMessageTrialVersionQuestion {
            get {
                return ResourceManager.GetString("MessageBoxMessageTrialVersionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? Current image is not saved and will be lost..
        /// </summary>
        public static string MessageBoxMessageUnsavedImageQuestion {
            get {
                return ResourceManager.GetString("MessageBoxMessageUnsavedImageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string PixelatePreviewPageButtonApplyContent {
            get {
                return ResourceManager.GetString("PixelatePreviewPageButtonApplyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIXELATE PARAMETERS.
        /// </summary>
        public static string PixelatePreviewPageTextBlockPageCommentText {
            get {
                return ResourceManager.GetString("PixelatePreviewPageTextBlockPageCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel size:.
        /// </summary>
        public static string PixelatePreviewPageTextBlockSliderCommentText {
            get {
                return ResourceManager.GetString("PixelatePreviewPageTextBlockSliderCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string SketchPreviewPageButtonApplyContent {
            get {
                return ResourceManager.GetString("SketchPreviewPageButtonApplyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKETCH PARAMETERS.
        /// </summary>
        public static string SketchPreviewPageTextBlockPageCommentText {
            get {
                return ResourceManager.GetString("SketchPreviewPageTextBlockPageCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation:.
        /// </summary>
        public static string SketchPreviewPageTextBlockSliderCommentText {
            get {
                return ResourceManager.GetString("SketchPreviewPageTextBlockSliderCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush opacity:.
        /// </summary>
        public static string TextBlockBrushOpacityText {
            get {
                return ResourceManager.GetString("TextBlockBrushOpacityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush size:.
        /// </summary>
        public static string TextBlockBrushRadiusText {
            get {
                return ResourceManager.GetString("TextBlockBrushRadiusText", resourceCulture);
            }
        }
    }
}
